_id: EPsdOtdiTfe50lFB
_key: "!items!EPsdOtdiTfe50lFB"
effects: []
img: >-
  systems/cyberpunk-red-core/icons/compendium/the_12_days_of_gearmas/esporma_enviroment_suit.svg
name: Esporma Environment Suit
system:
  bodyLocation:
    ablation: 0
    sp: 8
  brand: ""
  concealable:
    concealable: false
    isConcealed: false
  description:
    value: |
      <p>
        Armored Radiation Suit. Protects the wearer from Radiation and comes with an
        Oxygen Tank that lasts for 30 minutes which can be refilled by spending an
        hour in clean air.
      </p>
      <p>Nanomachines restore 1SP every hour SP isn't lost on the armor</p>
  equipped: owned
  favorite: false
  headLocation:
    ablation: 0
    sp: 8
  installedItems:
    allowed: false
    allowedTypes:
      - itemUpgrade
    list: []
    slots: 0
    usedSlots: 0
  isBodyLocation: true
  isElectronic: false
  isHeadLocation: true
  isShield: false
  penalty: 0
  price:
    market: 5000
  providesHardening: false
  revealed: true
  shieldHitPoints:
    max: 0
    value: 0
  source:
    book: 12DoGear
    page: 3
  usage: toggled
type: armor
